-- M0-06 (NSO-285): apps origin. Generated by drizzle-kit, then hand-edited:
-- the `team` visibility cannot be enforced on an app host (app hosts never read
-- the dashboard session), so existing `team` apps become `password` apps —
-- fail closed: with no password set nobody passes the gate until the owner sets one.
ALTER TABLE "apps" ALTER COLUMN "visibility" SET DATA TYPE text;--> statement-breakpoint
UPDATE "apps" SET "visibility" = 'password' WHERE "visibility" = 'team';--> statement-breakpoint
ALTER TABLE "apps" ALTER COLUMN "visibility" SET DEFAULT 'public'::text;--> statement-breakpoint
DROP TYPE "public"."app_visibility";--> statement-breakpoint
CREATE TYPE "public"."app_visibility" AS ENUM('public', 'password');--> statement-breakpoint
ALTER TABLE "apps" ALTER COLUMN "visibility" SET DEFAULT 'public'::"public"."app_visibility";--> statement-breakpoint
ALTER TABLE "apps" ALTER COLUMN "visibility" SET DATA TYPE "public"."app_visibility" USING "visibility"::"public"."app_visibility";--> statement-breakpoint
ALTER TABLE "apps" ADD COLUMN "frame_ancestors" text;
