-- M1-01 (NSO-287): platform modules. Generated by drizzle-kit. module_configs =
-- per-app module configuration (+ one pending change awaiting the owner's
-- confirmation); module_secrets = envelope-encrypted per-app module secrets
-- (dashboard-only writes, never returned by any API). audit_actor_kind gains
-- 'end_user' for module actions of an app's signed-in end users (ADD VALUE is
-- fine inside the migration transaction on PG 12+: nothing uses it in-txn).
ALTER TYPE "public"."audit_actor_kind" ADD VALUE 'end_user';--> statement-breakpoint
CREATE TABLE "module_configs" (
	"app_id" text NOT NULL,
	"module" text NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"pending" jsonb,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "module_configs_app_id_module_pk" PRIMARY KEY("app_id","module")
);
--> statement-breakpoint
CREATE TABLE "module_secrets" (
	"app_id" text NOT NULL,
	"module" text NOT NULL,
	"name" text NOT NULL,
	"ciphertext" text NOT NULL,
	"iv" text NOT NULL,
	"auth_tag" text NOT NULL,
	"wrapped_dek" text NOT NULL,
	"kek_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "module_secrets_app_id_module_name_pk" PRIMARY KEY("app_id","module","name")
);
--> statement-breakpoint
ALTER TABLE "module_configs" ADD CONSTRAINT "module_configs_app_id_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "module_secrets" ADD CONSTRAINT "module_secrets_app_id_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;