-- NSO-292 (M3-01): custom domains. Generated by drizzle-kit. Additive only.
-- Partial unique indexes: one VERIFIED row per hostname instance-wide (an
-- unverified claim never blocks the domain's real owner) and at most one
-- primary (redirect target) domain per app.
CREATE TABLE "domains" (
	"id" text PRIMARY KEY NOT NULL,
	"app_id" text NOT NULL,
	"hostname" text NOT NULL,
	"verification_token" text NOT NULL,
	"verified_at" timestamp,
	"last_check_at" timestamp,
	"last_error" text,
	"cert_state" text DEFAULT 'none' NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "domains" ADD CONSTRAINT "domains_app_id_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "domains_app_hostname_uq" ON "domains" USING btree ("app_id","hostname");--> statement-breakpoint
CREATE UNIQUE INDEX "domains_verified_hostname_uq" ON "domains" USING btree ("hostname") WHERE "domains"."verified_at" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "domains_primary_uq" ON "domains" USING btree ("app_id") WHERE "domains"."is_primary";--> statement-breakpoint
CREATE INDEX "domains_hostname_idx" ON "domains" USING btree ("hostname");