-- NSO-340: the public gallery. Generated by drizzle-kit, then the backfill
-- was added by hand. Additive only.
-- apps.published_at = when the production host last started serving a
-- version (publish sets it, unpublish / takedown clear it); backfilled from
-- the newest `app.publish` audit row, else the published version's creation.
-- Millisecond precision (the gallery cursor round-trips it through JS Date).
-- gallery_listed / gallery_description = the owner's opt-in (dashboard);
-- gallery_hidden_at = a super-admin hid the entry.
ALTER TABLE "apps" ADD COLUMN "published_at" timestamp;--> statement-breakpoint
ALTER TABLE "apps" ADD COLUMN "gallery_listed" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "apps" ADD COLUMN "gallery_description" text;--> statement-breakpoint
ALTER TABLE "apps" ADD COLUMN "gallery_hidden_at" timestamp;--> statement-breakpoint
CREATE INDEX "apps_gallery_idx" ON "apps" USING btree ("published_at" DESC NULLS LAST,"slug" DESC NULLS LAST) WHERE "apps"."gallery_listed";--> statement-breakpoint
UPDATE "apps" AS a SET "published_at" = date_trunc('milliseconds', COALESCE(
	(SELECT max(l."created_at") FROM "audit_log" l
		WHERE l."workspace_id" = a."workspace_id" AND l."subject_type" = 'app'
			AND l."target" = a."slug" AND l."action" = 'app.publish'),
	(SELECT v."created_at" FROM "app_versions" v WHERE v."id" = a."published_version_id"),
	now()
)) WHERE a."published_version_id" IS NOT NULL;
