-- NSO-346: opt-in platform modules a super-admin enabled per workspace
-- (dashboard). Generated by drizzle-kit. Additive only. A default module never
-- has a row; the limits provider's MODULE_ENABLED_<NAME> overrides a row.
CREATE TABLE "workspace_modules" (
	"workspace_id" text NOT NULL,
	"module" text NOT NULL,
	"enabled_by" text,
	"enabled_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "workspace_modules_workspace_id_module_pk" PRIMARY KEY("workspace_id","module")
);
--> statement-breakpoint
ALTER TABLE "workspace_modules" ADD CONSTRAINT "workspace_modules_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workspace_modules" ADD CONSTRAINT "workspace_modules_enabled_by_users_id_fk" FOREIGN KEY ("enabled_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;