/**
 * @drobek/modules — the platform module contract and runtime (M1-01).
 *
 * A module is PLATFORM code the operator installs (`DROBEK_MODULES`): server
 * routes under `/__drobek/v1/<module>/…` on the app hosts, a slice of the
 * browser SDK (`import { drobek } from 'drobek'`), a per-app config the agent
 * sets with `configure_module`, and a skill the agent reads with `skill_info`.
 * App code is never executed by the server — only modules are.
 *
 * Module authors: `defineModule`, `z`, `respond`, `ModuleError` (+ types,
 * including `DB`, `Logger` and `SdkCore`, so a module needs no other drobek
 * package); tests: `@drobek/modules/testing`. The contract is docs/MODULES.md.
 */
export { z } from 'zod';
export type { DB } from '@drobek/db';
export type { Logger } from '@drobek/core';
export type { SdkCore } from '@drobek/sdk';
export {
  MODULE_CONTRACT_VERSION,
  MODULE_ERROR_CODE_RE,
  MODULE_NAME_RE,
  SLOT_NAME_RE,
  RECORDS_IMPORT_MAX_ROWS,
  defineModule,
  isDefinedModule,
  respond,
  type AccessDecision,
  type AnyModule,
  normalizeConfirmItems,
  type ConfirmContext,
  type ConfirmItem,
  type ConfirmRole,
  type ConfirmedContext,
  type ComposedModuleParts,
  type DrobekModule,
  type EmailKind,
  type EmailMessage,
  type EmailRecipient,
  type EndUser,
  type EndUserAuthority,
  type EndUserCallbackApp,
  type EndUserCallbackInput,
  type EndUserCallbackResult,
  type EndUserListQuery,
  type EndUserPage,
  type EndUserRecord,
  type FilesAuthority,
  type OwnerFile,
  type OwnerFilesPage,
  type OwnerSubmission,
  type OwnerView,
  type SubmissionsAuthority,
  type SubmissionsPage,
  type SubmissionsQuery,
  type HookApp,
  type Limits,
  type MailAuthority,
  type MailEnvelope,
  type MailPrepareInput,
  type ModuleAvailability,
  type ModuleComposeInput,
  type ModuleContext,
  type ModuleDashboard,
  type ModuleDashboardEditor,
  type ModuleErrorDoc,
  type ModuleHooks,
  type ModuleAppView,
  type ModuleLimit,
  type ModuleMigrations,
  type ModuleRequest,
  type ModuleResponse,
  type ModuleRouter,
  type ModuleSdk,
  type ModuleSecretDoc,
  type ModuleServices,
  type ModuleSkill,
  type ModuleSlot,
  type Principal,
  type RateLimitResult,
  type RecordsAuthority,
  type RecordsCollection,
  type RecordsPage,
  type RecordsQuery,
  type RecordsView,
  type RouteHandler,
  type RouteOptions,
  type RouteRateLimit,
  type Rule,
  type UploadedFile,
} from './contract.js';
export {
  AUTH_PROVIDER_ID_RE,
  EMAIL_PROVIDER_ID,
  authIdentitySchema,
  authProviderSchema,
  authSignedInObserverSchema,
  defineAuthProvider,
  defineSignInObserver,
  type AuthIdentity,
  type AuthProvider,
  type AuthProviderBeginInput,
  type AuthProviderBeginResult,
  type AuthProviderCallbackInput,
  type AuthProviderSecretDoc,
  type AuthProviderSecrets,
  type AuthSignInEvent,
  type AuthSignedInObserver,
} from './auth-provider.js';
export { CORE_ERROR_CODES, MODULE_ERROR_CODES, ModuleError, isModuleError, moduleNotEnabled, skillHint, issuePaths, type ModuleErrorBody, type ModuleErrorCode } from './errors.js';
export { RULE_TOKENS, decideAccess, isValidRule, parseRule, ruleIsPublic } from './rules.js';
/** Per-client-IP bucket keys for a module's own per-IP limits (null = no resolved IP → skip it; NSO-328). */
export { perIpLimitKey } from '@drobek/core';
/** Byte sniffing shared with app assets (NSO-358): a module decides a stored file's type from its bytes. */
export { hasControlBytes, looksLikeSvg, sniffSignature, type SniffedType } from '@drobek/core';
export { mergePatch, jsonEqual } from './merge-patch.js';
export { Lru, jsonKey, stableJson } from './memo.js';
export {
  CORE_LIMITS,
  LIMITS_CACHE_TTL_SEC,
  LIMITS_SIGNATURE_HEADER,
  LIMITS_TIMESTAMP_HEADER,
  createLimitsProvider,
  limitsProviderConfigError,
  moduleEnabledLimitName,
  signLimitsRequest,
  type LimitsProvider,
} from './limits.js';
export {
  END_USER_COOKIE,
  END_USER_COOKIE_INSECURE,
  END_USER_SESSION_TTL_SEC,
  END_USER_TOKEN_RE,
  cookiePrincipalResolver,
  createEndUserSession,
  destroyEndUserSession,
  endUserCookieHeader,
  endUserCookieName,
  endUserCookiesSecure,
  endUserEpochKey,
  endUserSessionKey,
  loadEndUserSession,
  parseEndUserSession,
  readEndUserToken,
  renewEndUserSession,
  revokeEndUserSessions,
  type EndUserRedis,
  type CurrentEndUser,
  type EndUserSession,
  type PrincipalResolver,
} from './principal.js';
export { SECRET_NAME_RE, SECRET_MAX_BYTES, SecretStoreError, deleteModuleSecret, getModuleSecret, secretsSet, secretsStatus, setModuleSecret } from './secrets.server.js';
export { readConfigRow, type ConfigRow, type PendingChange } from './configs.server.js';
export { PENDING_MAIL_WINDOW_MS, pendingMail, pendingMailKey, type PendingMailModule } from './pending-mail.js';
export {
  BACKEND_IMPORT_SKILLS,
  PLATFORM_SKILL_NAME,
  generalSkillsDir,
  loadGeneralSkills,
  parseSkillMarkdown,
  skillForImport,
  type SkillEntry,
} from './skills.js';
export {
  BEACON_SCRIPT_PATH,
  SDK_PATH,
  SDK_TYPES_PATH,
  buildBeaconScript,
  buildSdk,
  inlineSpecifier,
  sdkDeclarations,
  type BeaconScript,
  type SdkBundle,
} from './sdk-build.js';
export { EMAIL_RE, MAX_EMAIL_TEXT, capEmailText, emailKind, recipientRefs, resolveRecipients, sanitizeSubject, type RecipientSources } from './email.js';
export {
  MAIL_COUNTER_KEYS,
  MAIL_PAUSE_KEYS,
  mailAppCounterKey,
  mailBudgets,
  mailGuardConfigFromEnv,
  memoryMailGuard,
  memoryMailGuardRedis,
  redisMailGuard,
  type MailBudgets,
  type MailClass,
  type MailGuard,
  type MailGuardConfig,
  type MailGuardMeta,
  type MailGuardRedis,
} from './mail-guard.js';
export { MAX_FILE_HEAD_BYTES, multipartBoundary, parseMultipart, streamMultipartFile } from './multipart.js';
export { SDK_HEADER, DEFAULT_MAX_BODY_BYTES, isReadable, type PipelineRequest, type PipelineResult } from './router.js';
export { csvChunks } from './csv-stream.js';
export {
  ModuleLoadError,
  RESERVED_MODULE_NAMES,
  checkErrorCodes,
  checkModuleSet,
  checkRequires,
  collectContributions,
  composeModule,
  effectiveConfigDefaults,
  moduleDefaultsEnvName,
  endUserAuthorityOf,
  mailAuthorityOf,
  recordsAuthorityOf,
  submissionsAuthorityOf,
  filesAuthorityOf,
  loadModules,
  loadModuleSet,
  packageNameFor,
  parseModuleList,
  type LoadedModules,
  type ModuleOrigin,
  type ModuleSource,
  type SlotContribution,
} from './registry.js';
export { DEFAULT_MODULES_DIR } from './dir-modules.js';
export {
  ModuleRuntime,
  activeModules,
  appOwnerEmails,
  confirmUrl,
  loadModuleRuntime,
  memoryRateLimiter,
  moduleJournalTable,
  moduleRuntime,
  redisRateLimiter,
  setModuleRuntimeForTests,
  smtpEmailTransport,
  type AppModuleState,
  type BoundEndUsers,
  type BoundFiles,
  type BoundRecords,
  type BoundSubmissions,
  type ConfigureInput,
  type ConfigureResult,
  type DecisionInput,
  type EmailTransport,
  type ModuleDashboardView,
  type PendingView,
  type TransportMessage,
  type LoadRuntimeOptions,
  type ModuleErrorSection,
  type ModuleSummary,
  type ModuleFacts,
  type PlatformApp,
  type PlatformRequest,
  type RateLimiter,
  type RuntimeDeps,
  type SkillInfo,
  type SkillListItem,
  type WorkspaceModuleSource,
  type WorkspaceModuleState,
} from './runtime.js';
