/**
 * The public module contract: everything a module author imports from
 * `@drobek/modules` (npm `@freema/drobek-modules`). It never reaches the
 * runtime or the loader (public-boundary.test.ts); its published
 * declarations are snapshotted (create-drobek-module scaffold.test.ts).
 * docs/MODULES.md "Public API and semver" is its semver policy.
 */
export { z } from 'zod';
export type { DB } from '@drobek/db';
export type { Logger } from '@drobek/core';
export type { SdkCore } from '@drobek/sdk';
export {
  JOB_MAX_INTERVAL_MS,
  JOB_MIN_INTERVAL_MS,
  JOB_NAME_RE,
  MODULE_CONTRACT_VERSION,
  MODULE_ERROR_CODE_RE,
  MODULE_NAME_RE,
  SLOT_NAME_RE,
  RECORDS_IMPORT_MAX_ROWS,
  defineModule,
  isDefinedModule,
  parseJobInterval,
  respond,
  type AccessDecision,
  type AnyModule,
  type AppJob,
  type AppJobContext,
  normalizeConfirmItems,
  type ConfirmContext,
  type ConfirmItem,
  type ConfirmRole,
  type ConfirmedContext,
  type ComposedModuleParts,
  type DrobekModule,
  type EmailKind,
  type EmailMessage,
  type EmailRecipient,
  type EndUser,
  type EndUserAuthority,
  type EndUserCallbackApp,
  type EndUserCallbackInput,
  type EndUserCallbackResult,
  type EndUserListQuery,
  type EndUserPage,
  type EndUserRecord,
  type FilesAuthority,
  type OwnerFile,
  type OwnerFilesPage,
  type OwnerSubmission,
  type OwnerView,
  type SubmissionsAuthority,
  type SubmissionsPage,
  type SubmissionsQuery,
  type HookApp,
  type JobContextBase,
  type JobInterval,
  type Limits,
  type MailAuthority,
  type MailEnvelope,
  type MailPrepareInput,
  type ModuleAvailability,
  type ModuleComposeInput,
  type ModuleContext,
  type ModuleDashboard,
  type ModuleDashboardEditor,
  type ModuleErrorDoc,
  type ModuleHooks,
  type ModuleJob,
  type ModuleAppView,
  type ModuleLimit,
  type ModuleMigrations,
  type ModuleRequest,
  type ModuleResponse,
  type ModuleRouter,
  type ModuleSdk,
  type ModuleSecretDoc,
  type ModuleServices,
  type ModuleSkill,
  type ModuleSlot,
  type Principal,
  type RateLimitResult,
  type RecordsAuthority,
  type RecordsCollection,
  type RecordsImportOptions,
  type RecordsImportResult,
  type RecordsPage,
  type RecordsQuery,
  type RecordsView,
  type RouteHandler,
  type RouteOptions,
  type RouteRateLimit,
  type Rule,
  type ServerJob,
  type ServerJobContext,
  type SyncAuthority,
  type SyncRun,
  type SyncSourceState,
  type UploadedFile,
  type UpstreamRequest,
  type UpstreamResponse,
  type UpstreamsAuthority,
} from './contract.js';
export {
  AUTH_PROVIDER_API_VERSION,
  AUTH_PROVIDER_ID_RE,
  AUTH_RESERVED_CONFIG_KEYS,
  EMAIL_PROVIDER_ID,
  authIdentitySchema,
  authProviderSchema,
  authSignedInObserverSchema,
  defineAuthProvider,
  defineSignInObserver,
  type AuthIdentity,
  type AuthProvider,
  type AuthProviderBeginInput,
  type AuthProviderBeginResult,
  type AuthProviderCallbackInput,
  type AuthProviderSecretDoc,
  type AuthProviderSecrets,
  type AuthSignInEvent,
  type AuthSignedInObserver,
} from './auth-provider.js';
export { EMAIL_TRANSPORT_SLOT, defineEmailTransport, emailTransportSchema } from './email-transport-slot.js';
export {
  EMAIL_SEND_ERROR_CODES,
  EMAIL_TRANSPORT_API_VERSION,
  EmailSendError,
  type EmailSendErrorCode,
  type EmailTransportContext,
  type EmailTransportMessage,
  type ModuleEmailTransport,
} from '@drobek/email';
export { ERROR_REPORTER_SLOT, defineErrorReporter, errorReporterSchema } from './error-reporter-slot.js';
export {
  ERROR_REPORTER_API_VERSION,
  type ErrorReportContext,
  type ErrorReportEvent,
  type ErrorReportKind,
  type ErrorReporter,
  type ErrorReporterContext,
} from '@drobek/core';
export { CORE_ERROR_CODES, MODULE_ERROR_CODES, ModuleError, isModuleError, moduleNotEnabled, skillHint, issuePaths, type ModuleErrorBody, type ModuleErrorCode } from './errors.js';
export { RULE_TOKENS, decideAccess, isValidRule, parseRule, ruleIsPublic } from './rules.js';
/** Per-client-IP bucket keys for a module's own per-IP limits (null = no resolved IP → skip it). */
export { perIpLimitKey } from '@drobek/core';
/** Byte sniffing shared with app assets: a module decides a stored file's type from its bytes. */
export { hasControlBytes, looksLikeSvg, sniffSignature, type SniffedType } from '@drobek/core';
