/**
 * Shared inline styles of the Modules tab (M2-02) — the dashboard's minimal
 * look; form controls from the shared layout (NSO-342). The pages render
 * inside <AppPage>.
 */
import { controls, mergeStyles } from '@drobek/tenancy/layout';

export const ui = {
  /** The tab's own title under the app header. */
  title: { fontSize: '1.15rem', margin: '1.75rem 0 0.25rem' },
  h2: { fontSize: '1.15rem', marginTop: '2.25rem', marginBottom: '0.5rem' },
  hint: { color: '#555', marginTop: 0, fontSize: '0.95rem' },
  muted: { color: '#8a8a8e' },
  small: { fontSize: '0.82rem', color: '#71717a' },
  mono: { fontFamily: 'ui-monospace, monospace', fontSize: '0.85rem' },
  badge: {
    display: 'inline-block',
    padding: '0.1rem 0.55rem',
    fontSize: '0.72rem',
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    borderRadius: '999px',
    border: '1px solid #d4d4d8',
    color: '#3f3f46',
    background: '#fafafa',
  },
  okBadge: {
    display: 'inline-block',
    padding: '0.1rem 0.55rem',
    fontSize: '0.72rem',
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    borderRadius: '999px',
    color: '#166534',
    background: '#dcfce7',
    border: '1px solid #bbf7d0',
  },
  warnBadge: {
    display: 'inline-block',
    padding: '0.1rem 0.55rem',
    fontSize: '0.72rem',
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    borderRadius: '999px',
    color: '#92400e',
    background: '#fef3c7',
    border: '1px solid #fde68a',
  },
  panel: { border: '1px solid #e4e4e7', borderRadius: '10px', padding: '0.9rem 1rem', background: '#fcfcfd', marginBottom: '0.9rem' },
  pendingPanel: { border: '1px solid #fcd34d', borderRadius: '10px', padding: '0.9rem 1rem', background: '#fffbeb', marginBottom: '0.9rem' },
  field: { display: 'block', marginBottom: '0.85rem' },
  label: { display: 'block', fontWeight: 600, fontSize: '0.9rem' },
  desc: { display: 'block', fontSize: '0.8rem', color: '#71717a' },
  input: mergeStyles(controls.input, { width: '100%' }),
  textarea: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '0.4rem 0.55rem',
    fontSize: '0.85rem',
    fontFamily: 'ui-monospace, monospace',
    border: '1px solid #d4d4d8',
    borderRadius: '7px',
    background: '#fff',
    minHeight: '5.5rem',
  },
  inputError: { borderColor: '#f87171', background: '#fef2f2' },
  fieldset: { border: '1px solid #e4e4e7', borderRadius: '8px', padding: '0.6rem 0.8rem 0.2rem', margin: '0 0 0.85rem' },
  legend: { fontWeight: 700, fontSize: '0.85rem', padding: '0 0.3rem' },
  fieldError: { color: '#991b1b', fontSize: '0.82rem', margin: '0.2rem 0 0' },
  error: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#991b1b',
    borderRadius: '8px',
    padding: '0.6rem 0.75rem',
    fontSize: '0.9rem',
    margin: '0.5rem 0',
  },
  notice: {
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    color: '#166534',
    borderRadius: '8px',
    padding: '0.6rem 0.75rem',
    fontSize: '0.9rem',
    margin: '0.5rem 0 1rem',
  },
  button: controls.button,
  secondaryButton: controls.secondaryButton,
  // Long labels ("Remove collection (its records become unreachable)") wrap on a phone.
  dangerButton: mergeStyles(controls.secondaryButton, {
    color: '#991b1b',
    border: '1px solid #fecaca',
    whiteSpace: 'normal',
    height: 'auto',
    minHeight: controls.secondaryButton.height,
    padding: '0.3rem 0.9rem',
    maxWidth: '100%',
  }),
  row: { display: 'flex', gap: '0.5rem', alignItems: 'center', flexWrap: 'wrap' },
  tableWrap: { overflowX: 'auto', maxWidth: '100%' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '0.88rem', margin: '0.4rem 0 0.6rem' },
  th: {
    textAlign: 'left',
    borderBottom: '1px solid #e4e4e7',
    padding: '0.4rem 0.5rem 0.4rem 0',
    color: '#555',
    fontSize: '0.76rem',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  td: { borderBottom: '1px solid #f0f0f2', padding: '0.45rem 0.5rem 0.45rem 0', verticalAlign: 'top' },
  center: { textAlign: 'center' },
} as const;
